export const searchStyles = {
  buttonCommon: [
    "justify-between",
    "h-16",
    "mt-2",
    "px-4",
    "text-start",
    "bg-gray-200",
    "dark:bg-base-dark",
  ],
  buttonHoverFocusActive: [
    "data-[hover=true]:bg-bittersweet-400",
    "dark:data-[hover=true]:bg-cerise-red-600",
    "data-[focus=true]:bg-bittersweet-400",
    "dark:data-[focus=true]:bg-cerise-red-600",
    "data-[active=true]:bg-bittersweet-400",
    "dark:data-[active=true]:bg-cerise-red-600",
  ],
  textHoverFocusActive: [
    "group-data-[hover=true]:text-white",
    "group-data-[focus=true]:text-white",
    "group-data-[active=true]:text-white",
  ],
  buttonTextColor: [
    "text-base-color-m",
    "dark:text-base-color-dark-m",
    "hover:!text-white",
  ],
  iconColor: [
    "size-6",
    "text-base-color-d",
    "dark:text-base-color-dark-d",
    "group-data-[hover=true]:text-white",
    "group-data-[focus=true]:text-white",
    "group-data-[active=true]:text-white",
  ],
  inputWrapper: [
    "h-14",
    "bg-transparent",
    "data-[hover=true]:bg-transparent",
    "group-data-[focus=true]:bg-transparent",
    "text-base-color-m",
    "dark:text-base-color-dark-m",
    "group-data-[focus-visible=true]:ring-0",
    "group-data-[focus-visible=true]:ring-offset-0",
  ],
  input: ["placeholder:text-lg"],
  modalHeader: ["flex", "items-center", "w-full", "pl-2", "pr-4"],
  modalContent: [
    "relative",
    "px-4",
    "my-2",
    "pb-8",
    "overflow-y-auto",
    "max-h-[50vh]",
    "scrollbar-hide",
    "md:scrollbar-default",
    "custom-scroll",
    "v2",
  ],
  noResults: [
    "flex",
    "flex-col",
    "text-center",
    "items-center",
    "justify-center",
    "h-32",
  ],
};
